from fastapi.testclient import TestClient

from app.api.routes import song
from app.main import app
from app.models.schemas import (
    ExtendRequest,
    ExtendResponse,
    GenerateRequest,
    GenerateResponse,
)


class _FakeProviderRouter:
    configured = ["gemini"]
    default_provider = "auto"
    auto_order = ["gemini", "openai"]


class _FakeSongService:
    provider_router = _FakeProviderRouter()

    def generate(self, payload: GenerateRequest) -> GenerateResponse:
        return GenerateResponse(
            title=f"Generated: {payload.topic}",
            style="Melancholic, driving, analog synth, female vocals, synthwave, 44.1kHz, Wide Stereo, Clean Mix",
            lyrics="[Verse]\nNeon rain on city glass",
            explanation="Generated by fake service for route tests.",
            providerUsed="gemini",
            modelUsed="gemini-2.0-flash",
        )

    def extend(self, payload: ExtendRequest) -> ExtendResponse:
        return ExtendResponse(
            addedLyrics="[Bridge]\nSignals fade into dawn",
            providerUsed="gemini",
            modelUsed="gemini-2.0-flash",
        )


client = TestClient(app)


def test_song_providers_route(monkeypatch) -> None:
    monkeypatch.setattr(song, "get_song_service", lambda: _FakeSongService())
    response = client.get("/api/song/providers")
    assert response.status_code == 200
    assert response.json() == {
        "configured": ["gemini"],
        "defaultProvider": "auto",
        "autoOrder": ["gemini", "openai"],
    }


def test_song_generate_route(monkeypatch) -> None:
    monkeypatch.setattr(song, "get_song_service", lambda: _FakeSongService())
    response = client.post(
        "/api/song/generate",
        json={
            "topic": "Neon rain",
            "genre": "Synthwave",
            "mood": "Melancholic",
            "voice": "Female",
            "tempo": "110 BPM",
            "structure": "Pop",
            "language": "English",
            "isInstrumental": False,
            "provider": "auto",
        },
    )
    assert response.status_code == 200
    body = response.json()
    assert body["title"].startswith("Generated:")
    assert body["providerUsed"] == "gemini"


def test_song_extend_route(monkeypatch) -> None:
    monkeypatch.setattr(song, "get_song_service", lambda: _FakeSongService())
    response = client.post(
        "/api/song/extend",
        json={
            "currentLyrics": "[Verse]\nNeon rain",
            "topic": "Neon rain",
            "style": "Synthwave",
            "language": "English",
            "provider": "auto",
        },
    )
    assert response.status_code == 200
    body = response.json()
    assert body["addedLyrics"].startswith("[Bridge]")
    assert body["providerUsed"] == "gemini"
